-- Criando a tabela TB_EMITENTE
CREATE TABLE TB_EMITENTE (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    CNPJ VARCHAR2(14) NOT NULL,
    ENDERECO VARCHAR2(255) NOT NULL,
    TELEFONE VARCHAR2(20),
    EMAIL VARCHAR2(255)
);

-- Criando a tabela TB_DESTINATARIO
CREATE TABLE TB_DESTINATARIO (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    CPF_CNPJ VARCHAR2(14) NOT NULL,
    ENDERECO VARCHAR2(255) NOT NULL,
    TELEFONE VARCHAR2(20),
    EMAIL VARCHAR2(255)
);

-- Criando a tabela TB_PRODUTO
CREATE TABLE TB_PRODUTO (
    ID NUMBER PRIMARY KEY,
    DESCRICAO VARCHAR2(255) NOT NULL,
    CODIGO_BARRAS VARCHAR2(13) NOT NULL,
    NCM VARCHAR2(8) NOT NULL,
    CEST VARCHAR2(7),
    UNIDADE VARCHAR2(3) NOT NULL,
    VALOR_UNITARIO NUMBER(10,2) NOT NULL
);

-- Criando a tabela TB_NOTA_FISCAL
CREATE TABLE TB_NOTA_FISCAL (
    ID NUMBER PRIMARY KEY,
    NUMERO VARCHAR2(20) NOT NULL,
    SERIE VARCHAR2(5) NOT NULL,
    DATA_EMISSAO DATE NOT NULL,
    VALOR_TOTAL NUMBER(15,2),
    EMITENTE_ID NUMBER REFERENCES TB_EMITENTE(ID),
    DESTINATARIO_ID NUMBER REFERENCES TB_DESTINATARIO(ID),
    STATUS VARCHAR2(20) NOT NULL,
    CHAVE_ACESSO VARCHAR2(44),
    TIPO_OPERACAO VARCHAR2(20)
);

-- Criando a tabela TB_ITEM_NOTA_FISCAL
CREATE TABLE TB_ITEM_NOTA_FISCAL (
    ID NUMBER PRIMARY KEY,
    NOTA_FISCAL_ID NUMBER REFERENCES TB_NOTA_FISCAL(ID),
    PRODUTO_ID NUMBER REFERENCES TB_PRODUTO(ID),
    QUANTIDADE NUMBER(10,2),
    VALOR_UNITARIO NUMBER(10,2)
);

-- Criando a tabela TB_TRIBUTOS
CREATE TABLE TB_TRIBUTOS (
    ID NUMBER PRIMARY KEY,
    NOTA_FISCAL_ID NUMBER REFERENCES TB_NOTA_FISCAL(ID),
    ICMS NUMBER(10,2),
    IPI NUMBER(10,2),
    PIS NUMBER(10,2),
    COFINS NUMBER(10,2)
);

-- Criando a tabela TB_TRANSPORTADORA
CREATE TABLE TB_TRANSPORTADORA (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    CNPJ VARCHAR2(14) NOT NULL,
    ENDERECO VARCHAR2(255) NOT NULL,
    TELEFONE VARCHAR2(20),
    EMAIL VARCHAR2(255)
);

-- Criando a tabela TB_FRETE
CREATE TABLE TB_FRETE (
    ID NUMBER PRIMARY KEY,
    NOTA_FISCAL_ID NUMBER REFERENCES TB_NOTA_FISCAL(ID),
    TRANSPORTADORA_ID NUMBER REFERENCES TB_TRANSPORTADORA(ID),
    VALOR_FRETE NUMBER(10,2),
    PLACA_VEICULO VARCHAR2(7),
    UF_VEICULO VARCHAR2(2),
    PESO_BRUTO NUMBER(10,2),
    PESO_LIQUIDO NUMBER(10,2)
);

-- Criando índices
CREATE INDEX IDX_NOTA_FISCAL_NUMERO ON TB_NOTA_FISCAL(NUMERO);
CREATE INDEX IDX_ITEM_NOTA_FISCAL_NOTA ON TB_ITEM_NOTA_FISCAL(NOTA_FISCAL_ID);
CREATE INDEX IDX_PRODUTO_CODIGO_BARRAS ON TB_PRODUTO(CODIGO_BARRAS);
CREATE INDEX IDX_TRANSPORTADORA_CNPJ ON TB_TRANSPORTADORA(CNPJ);




-- SCRIPT PARA CRIAÇÃO

-- Criar o usuário e conceder permissões (caso ainda não exista)
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER TAXINVOICE IDENTIFIED BY password';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO TAXINVOICE';
    EXECUTE IMMEDIATE 'ALTER USER TAXINVOICE QUOTA UNLIMITED ON USERS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1920 THEN -- Usuário já existe
            RAISE;
        END IF;
END;
/

-- Criar sequências para IDs automáticos
BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE TAXINVOICE.SEQ_EMITENTE START WITH 1 INCREMENT BY 1';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE TAXINVOICE.SEQ_DESTINATARIO START WITH 1 INCREMENT BY 1';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE TAXINVOICE.SEQ_PRODUTO START WITH 1 INCREMENT BY 1';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE TAXINVOICE.SEQ_NOTA_FISCAL START WITH 1 INCREMENT BY 1';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE TAXINVOICE.SEQ_ITEM_NOTA_FISCAL START WITH 1 INCREMENT BY 1';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE TAXINVOICE.SEQ_TRIBUTOS START WITH 1 INCREMENT BY 1';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE TAXINVOICE.SEQ_TRANSPORTADORA START WITH 1 INCREMENT BY 1';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE TAXINVOICE.SEQ_FRETE START WITH 1 INCREMENT BY 1';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN -- Sequência já existe
            RAISE;
        END IF;
END;
/

-- Criar tabelas usando DEFAULT para IDs automáticos
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE TAXINVOICE.TB_EMITENTE (
        ID NUMBER PRIMARY KEY DEFAULT TAXINVOICE.SEQ_EMITENTE.NEXTVAL,
        NOME VARCHAR2(255) NOT NULL,
        CNPJ VARCHAR2(14) NOT NULL,
        ENDERECO VARCHAR2(255) NOT NULL,
        TELEFONE VARCHAR2(20),
        EMAIL VARCHAR2(255)
    )';

    EXECUTE IMMEDIATE 'CREATE TABLE TAXINVOICE.TB_DESTINATARIO (
        ID NUMBER PRIMARY KEY DEFAULT TAXINVOICE.SEQ_DESTINATARIO.NEXTVAL,
        NOME VARCHAR2(255) NOT NULL,
        CPF_CNPJ VARCHAR2(14) NOT NULL,
        ENDERECO VARCHAR2(255) NOT NULL,
        TELEFONE VARCHAR2(20),
        EMAIL VARCHAR2(255)
    )';

    EXECUTE IMMEDIATE 'CREATE TABLE TAXINVOICE.TB_PRODUTO (
        ID NUMBER PRIMARY KEY DEFAULT TAXINVOICE.SEQ_PRODUTO.NEXTVAL,
        DESCRICAO VARCHAR2(255) NOT NULL,
        CODIGO_BARRAS VARCHAR2(13) NOT NULL,
        NCM VARCHAR2(8) NOT NULL,
        CEST VARCHAR2(7),
        UNIDADE VARCHAR2(3) NOT NULL,
        VALOR_UNITARIO NUMBER(10,2) NOT NULL
    )';

    EXECUTE IMMEDIATE 'CREATE TABLE TAXINVOICE.TB_NOTA_FISCAL (
        ID NUMBER PRIMARY KEY DEFAULT TAXINVOICE.SEQ_NOTA_FISCAL.NEXTVAL,
        NUMERO VARCHAR2(20) NOT NULL,
        SERIE VARCHAR2(5) NOT NULL,
        DATA_EMISSAO DATE NOT NULL,
        VALOR_TOTAL NUMBER(15,2),
        EMITENTE_ID NUMBER REFERENCES TAXINVOICE.TB_EMITENTE(ID),
        DESTINATARIO_ID NUMBER REFERENCES TAXINVOICE.TB_DESTINATARIO(ID),
        STATUS VARCHAR2(20) NOT NULL,
        CHAVE_ACESSO VARCHAR2(44),
        TIPO_OPERACAO VARCHAR2(20)
    )';

    EXECUTE IMMEDIATE 'CREATE TABLE TAXINVOICE.TB_ITEM_NOTA_FISCAL (
        ID NUMBER PRIMARY KEY DEFAULT TAXINVOICE.SEQ_ITEM_NOTA_FISCAL.NEXTVAL,
        NOTA_FISCAL_ID NUMBER REFERENCES TAXINVOICE.TB_NOTA_FISCAL(ID),
        PRODUTO_ID NUMBER REFERENCES TAXINVOICE.TB_PRODUTO(ID),
        QUANTIDADE NUMBER(10,2),
        VALOR_UNITARIO NUMBER(10,2)
    )';

    EXECUTE IMMEDIATE 'CREATE TABLE TAXINVOICE.TB_TRIBUTOS (
        ID NUMBER PRIMARY KEY DEFAULT TAXINVOICE.SEQ_TRIBUTOS.NEXTVAL,
        NOTA_FISCAL_ID NUMBER REFERENCES TAXINVOICE.TB_NOTA_FISCAL(ID),
        ICMS NUMBER(10,2),
        IPI NUMBER(10,2),
        PIS NUMBER(10,2),
        COFINS NUMBER(10,2)
    )';

    EXECUTE IMMEDIATE 'CREATE TABLE TAXINVOICE.TB_TRANSPORTADORA (
        ID NUMBER PRIMARY KEY DEFAULT TAXINVOICE.SEQ_TRANSPORTADORA.NEXTVAL,
        NOME VARCHAR2(255) NOT NULL,
        CNPJ VARCHAR2(14) NOT NULL,
        ENDERECO VARCHAR2(255) NOT NULL,
        TELEFONE VARCHAR2(20),
        EMAIL VARCHAR2(255)
    )';

    EXECUTE IMMEDIATE 'CREATE TABLE TAXINVOICE.TB_FRETE (
        ID NUMBER PRIMARY KEY DEFAULT TAXINVOICE.SEQ_FRETE.NEXTVAL,
        NOTA_FISCAL_ID NUMBER REFERENCES TAXINVOICE.TB_NOTA_FISCAL(ID),
        TRANSPORTADORA_ID NUMBER REFERENCES TAXINVOICE.TB_TRANSPORTADORA(ID),
        VALOR_FRETE NUMBER(10,2),
        PLACA_VEICULO VARCHAR2(7),
        UF_VEICULO VARCHAR2(2),
        PESO_BRUTO NUMBER(10,2),
        PESO_LIQUIDO NUMBER(10,2)
    )';

    -- Criar índices
    EXECUTE IMMEDIATE 'CREATE INDEX TAXINVOICE.IDX_NOTA_FISCAL_NUMERO ON TAXINVOICE.TB_NOTA_FISCAL(NUMERO)';
    EXECUTE IMMEDIATE 'CREATE INDEX TAXINVOICE.IDX_ITEM_NOTA_FISCAL_NOTA ON TAXINVOICE.TB_ITEM_NOTA_FISCAL(NOTA_FISCAL_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX TAXINVOICE.IDX_PRODUTO_CODIGO_BARRAS ON TAXINVOICE.TB_PRODUTO(CODIGO_BARRAS)';
    EXECUTE IMMEDIATE 'CREATE INDEX TAXINVOICE.IDX_TRANSPORTADORA_CNPJ ON TAXINVOICE.TB_TRANSPORTADORA(CNPJ)';

    -- Confirmar a transação
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Erro: ' || SQLERRM);
END;
/

-- Definir o schema padrão para a sessão atual
ALTER SESSION SET CURRENT_SCHEMA = TAXINVOICE;


